apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor-deployment
  namespace: dev
  labels:
    app: log-message-processor
    object: deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate  
  template:
    metadata:
      name: log-message-processor-pod
      labels:
        app: log-message-processor
        object: pod
    spec:
      containers:
        - name: log-message-processor-container
          image: dacostatapia/log-message-processor:v2
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: log_channel
            - name: ZIPKIN_URL
              value: http://zipkin-service:9411
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
  selector:
    matchLabels:
      app: log-message-processor
      object: pod
    