apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: dev
  labels:
    app: users-api
    object: deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: users-api-pod
      labels:
        app: users-api
        object: pod
    spec:
      containers:
        - name: users-api-container
          image: dacostatapia/users-api:v2
          env:
            - name: JWT_SECRET
              value: myfancysecret
            - name: SERVER_PORT
              value: "8083"
            - name: ZIPKIN_URL
              value: http://zipkin-service:9411
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"              
  selector:
    matchLabels:
      app: users-api
      object: pod

---

apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: users-api
    object: pod