apiVersion: v1
kind: Pod
metadata:
  name: auth-api
  namespace: dev
  labels:
    app: auth-api
spec:
  containers:
    - name: auth-api
      image: dacostatapia/auth-api:v2
      env:
        - name: AUTH_API_PORT
          value: "8000"
        - name: USERS_API_ADDRESS
          value: http://users-api-service:8083
        - name: JWT_SECRET
          value: myfancysecret
        - name: ZIPKIN_URL
          value: http://zipkin-service:9411

---

apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-api
    