apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: dacostatapia/frontend:v2
      env:
        - name: PORT
          value: "8080"
        - name: AUTH_API_ADDRESS
          value: http://auth-api-service:8000
        - name: TODOS_API_ADDRESS
          value: http://todos-api-service:8082          
        - name: ZIPKIN_URL
          value: http://zipkin-service:9411

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: frontend
