apiVersion: v1
kind: Pod
metadata:
  name: log-message-processor
  namespace: dev
  labels:
    app: log-message-processor
spec:
  containers:
    - name: log-message-processor
      image: dacostatapia/log-message-processor:v2
      env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin-service:9411