apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dev
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:7.0.5-alpine

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    