apiVersion: v1
kind: Pod
metadata:
  name: todos-api
  namespace: dev
  labels:
    app: todos-api
spec:
  containers:
    - name: todos-api
      image: dacostatapia/todos-api:v2
      env:
        - name: TODO_API_PORT
          value: "8082"
        - name: JWT_SECRET
          value: myfancysecret
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin-service:9411          

---

apiVersion: v1
kind: Service
metadata:
  name: todos-api-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: todos-api
    