apiVersion: v1
kind: Pod
metadata:
  name: users-api
  namespace: dev
  labels:
    app: users-api
spec:
  containers:
    - name: users-api
      image: dacostatapia/users-api:v2
      env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: ZIPKIN_URL
          value: http://zipkin-service:9411

---

apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: users-api
  