apiVersion: v1
kind: Pod
metadata:
  name: zipkin
  namespace: dev
  labels:
    app: zipkin
spec:
  containers:
    - name: zipkin
      image: openzipkin/zipkin:2.24.1

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: zipkin
    