apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
  labels:
    app: frontend
    object: deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
        object: pod
    spec:
      containers:
        - name: frontend-container
          image: dacostatapia/frontend:v2
          env:
            - name: PORT
              value: "8080"
            - name: AUTH_API_ADDRESS
              value: http://auth-api-service:8000
            - name: TODOS_API_ADDRESS
              value: http://todos-api-service:8082          
            - name: ZIPKIN_URL
              value: http://zipkin-service:9411
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
  selector:
    matchLabels:
      app: frontend
      object: pod

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  # type: NodePort # Local development
  type: LoadBalancer # Cloud development
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: frontend
    object: pod